---
- name: Stop Cluster
  hosts: localhost
  become: true
  become_method: enable
  #become_user: admin
  vars:
    host= "localhost"
  
  tasks:
  - name: uninstall nginx
    yum:
      name: nginx
      state: absent

  - name: stop nginx
    service:
     name: nginx
     state: stopped

  - name: print success message       
    debug:
      msg: "The Cluster {{host}} has been successfully Stopped."
...
